### ISSUE TITLE
Jubeat Button Board Connector EoL'd

### ISSUE THREAD

**Issue by sdshlanta** [veroxzik/jubeat-boards#2]
The connector on the Jubeat button PCB has been EoLed and is difficult to find from reputable sources.  This part on Digikey appears to be a good dimensional match for the old connector:

2SH-C-09-TR
(DKPN: 2057-2SH-C-09-TR-ND)
https://www.digikey.com/en/products/detail/adam-tech/2SH-C-09-TR/9830823

There are additional substitutes for it on the old connectors Digikey page as well.

https://www.digikey.com/en/products/detail/S9B-PH-K-S/455-1221-ND/608662#product-details-substitutes

Updating the readme with this information could save people upwards of 10s of minuets ;)

**Comment by veroxzik** [comment]
Thank you for bringing this to my attention! The change has been made.

**Comment by sdshlanta** [comment]
Awesome! thanks for addressing this so quickly!
